server:
  port: 3344
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          #uri: git@githup.com:Axiaopihai/springcloud-config.git
          uri: https://github.com/Axiaopihai/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true

