server:
  port: 8402
spring:
  application:
    name: cloud-alibaba-sentinel-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"